<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link rel="shortcut icon" type="image/x-icon" href="images/Logo.jpg" />
  <title>Valentin - Portfolio</title>
  <style>
    * {
      font-family: 'Poppins', sans-serif;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      scroll-behavior: smooth;
    }
    body {
      background-color: #000;
      color: #fff;
    }
    header {
      background-color: #000;
      width: 100%;
      position: fixed;
      top: 0;
      left: 0;
      z-index: 1000;
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 10px 200px;
      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }
    .logo {
      text-decoration: none;
      color: #0f2f88;
      text-transform: uppercase;
      font-weight: 700;
      font-size: 1.8em;
    }
    nav {
      display: flex;
      align-items: center;
    }
    nav a {
      color: #62a8ff;
      text-decoration: none;
      font-size: 1.1em;
      font-weight: 500;
      padding-left: 30px;
      transition: color 0.3s;
    }
    nav a:hover {
      color: #fff;
    }
    .language-tab {
      position: relative;
      cursor: pointer;
      margin-left: 20px;
      font-weight: 500;
      color: #62a8ff;
    }
    .language-options {
      position: absolute;
      top: 120%;
      left: 0;
      background-color: #111;
      border: 1px solid #ccc;
      display: none;
      min-width: 120px;
      box-shadow: 0 4px 8px rgba(0,0,0,0.1);
    }
    .language-tab:hover .language-options {
      display: block;
    }
    .language-options button {
      width: 100%;
      padding: 10px;
      background: none;
      border: none;
      text-align: left;
      cursor: pointer;
      color: #fff;
    }
    .language-options button:hover {
      background-color: #222;
    }
    section {
      padding: 120px 200px 60px;
    }
    .main {
      min-height: 100vh;
      /* background-image supprimée pour fond noir uni */
      display: flex;
      justify-content: center;
      align-items: center;
      text-align: center;
    }
    .main h1 {
      font-size: 3em;
      color: #fff;
    }
    .main h1 span {
      color: #69f;
    }
    .main p {
      font-size: 1.5em;
      color: #e0e0e0;
      margin-top: 15px;
      font-style: italic;
    }
    .title {
      text-align: center;
      font-size: 2.2em;
      font-weight: 800;
      margin-bottom: 30px;
    }
    .content {
      display: flex;
      justify-content: center;
      flex-wrap: wrap;
    }
    .card {
      background-color: #111;
      width: 300px;
      margin: 15px;
      padding: 25px;
      border-radius: 10px;
      box-shadow: 0 5px 25px rgba(0, 0, 0, 0.3);
      transition: transform 0.3s ease;
      text-align: center;
      color: #fff;
      position: relative;
    }
    .card:hover {
      transform: scale(1.05);
    }
    .icon {
      font-size: 3.5em;
      color: #5e41ff;
      margin-bottom: 15px;
    }
    .info h3 {
      font-size: 1.3em;
      font-weight: 700;
      margin-bottom: 10px;
    }
    .info p {
      font-size: 1em;
    }
    .footer {
      background-color: #000016;
      color: #fff;
      padding: 2em 200px;
      display: flex;
      justify-content: space-between;
      flex-wrap: wrap;
    }
    .footer-title {
      font-size: 1.3em;
      font-weight: 600;
    }
    .footer-title span {
      color: #5e41ff;
    }
    a {
      color: inherit;
      text-decoration: none;
    }

    /* === Media Query Mobile - uniquement adaptations === */
    @media (max-width: 768px) {
      header {
        padding: 10px 20px !important;
      }
      nav a {
        padding-left: 15px !important;
        font-size: 1em !important;
      }
      section {
        padding: 100px 20px 40px !important;
      }
      .main h1 {
        font-size: 2.2em !important;
      }
      .main p {
        font-size: 1.1em !important;
      }
      .content {
        flex-direction: column !important;
        align-items: center !important;
      }
      .card {
        width: 90% !important;
        margin: 10px 0 !important;
      }
      .footer {
        padding: 2em 20px !important;
      }
    }
  </style>
</head>
<body>
  <header>
    <a href="#" class="logo">Valentin</a>
    <nav>
      <a href="#about">À propos</a>
      <a href="#contact">Contact</a>
      <div class="language-tab">Langue
        <div class="language-options">
          <button onclick="alert('Langue changée vers : Français')">Français</button>
          <button onclick="alert('Language switched to: English')">Anglais</button>
        </div>
      </div>
    </nav>
  </header>

  <section class="main">
    <div>
      <h1>Bienvenue, je suis <span>Valentin</span></h1>
      <p>Lycéen qui découvre le codage</p>
    </div>
  </section>

  <section id="about">
    <h2 class="title">À propos de moi</h2>
    <div class="content">
      <a href="https://fr.wikipedia.org/wiki/Maurice_(pays)" target="_blank" class="card">
        <div class="icon"><i class="fas fa-flag"></i></div>
        <div class="info">
          <h3>Origine</h3>
          <p>Mauricien</p>
        </div>
      </a>
      <div class="card">
        <div class="icon"><i class="fas fa-language"></i></div>
        <div class="info">
          <h3>Langues</h3>
          <p>Français &amp; Anglais</p>
        </div>
      </div>
      <div class="card">
        <div class="icon"><i class="fas fa-user"></i></div>
        <div class="info">
          <h3>Âge</h3>
          <p>16 ans</p>
        </div>
      </div>
      <div class="card">
        <div class="icon"><i class="fas fa-code"></i></div>
        <div class="info">
          <h3>Codage</h3>
          <p>Page entièrement codée par moi</p>
        </div>
      </div>
    </div>
  </section>

  <section id="contact">
    <h2 class="title">Contact</h2>
    <div class="content">
      <div class="card">
        <div class="icon"><i class="fas fa-envelope"></i></div>
        <div class="info">
          <h3>Email</h3>
          <p><a href="mailto:valentinredoules8@gmail.com">valentinredoules8@gmail.com</a></p>
        </div>
      </div>
      <div class="card">
        <div class="icon"><i class="fas fa-phone"></i></div>
        <div class="info">
          <h3>Téléphone</h3>
          <p><a href="tel:0616219614">0616219614</a></p>
        </div>
      </div>
    </div>
  </section>

  <footer class="footer">
    <p class="footer-title">Copyright © <span>Valentin Redoules</span></p>
  </footer>
</body>
</html>
